import { Injectable } from '@nestjs/common';
import {
  LeadStatus,
  Prisma,
  Trip,
  TripStatus,
  TripVisit,
} from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { PaginatedResult } from '../../common/dto/response.dto';
import { SalesStaffService } from './sales-staff.service';
import { SalesLeadStatusService } from './sales-lead-status.service';
import { CreateTripDto } from './dto/create-trip.dto';
import { UpdateTripDto } from './dto/update-trip.dto';
import { ListTripsDto } from './dto/list-trips.dto';
import { TripVisitDto } from './dto/trip-visit.dto';
import {
  InvalidTripLeadException,
  TripNotFoundException,
  TripVisitNotFoundException,
} from './exceptions/sales-trip.exceptions';
import {
  TripDetail,
  TripListRow,
  TripRoadmap,
  TripVisitCounts,
} from './entities/trip.entity';

/** Trip status → the lead status it drives (unmapped = leave the lead as-is). */
const TRIP_TO_LEAD_STATUS: Partial<Record<TripStatus, LeadStatus>> = {
  [TripStatus.IN_PROGRESS]: LeadStatus.MEETING_IN_PROGRESS,
  [TripStatus.COMPLETED]: LeadStatus.MEETING_COMPLETED,
};

/**
 * Field-sales trips. Tenant-scoped + branch-level (CLAUDE.md §4.7): every query
 * carries `tenantId`/`branchId` and filters soft-deleted rows. The `tripCode`
 * (`TRP-#####`) is a per-tenant sequential code generated atomically. Visit
 * counts are derived from `TripVisit` rows (single source of truth); a trip may
 * be linked to the lead it was started from (Lead → many Trips).
 */
@Injectable()
export class SalesTripService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly staff: SalesStaffService,
    private readonly leadStatus: SalesLeadStatusService,
  ) {}

  /**
   * Create a trip at the active branch (the priority POST). Validates the
   * salesperson (any active staff member) and, when supplied, the `leadId`
   * against the caller's tenant/branch. The `tripCode` is generated by atomically
   * incrementing `Tenant.tripCounter` in the same transaction, so concurrent
   * creates never collide. Optional `visits` are seeded in the same transaction.
   * @param tenantId tenant scope
   * @param branchId active branch (from JWT)
   * @param dto validated trip payload (no code/tenant/branch — set here)
   * @param actorId person id of the creator (audit trail)
   * @returns the created trip enriched with names + derived counts
   * @throws InvalidSalespersonException if the salesperson is not active staff
   * @throws InvalidTripLeadException if `leadId` is invalid for the branch
   */
  async create(
    tenantId: string,
    branchId: string,
    dto: CreateTripDto,
    actorId?: string,
  ): Promise<TripDetail> {
    await this.staff.assertSalesperson(tenantId, dto.salespersonId);
    if (dto.leadId) {
      await this.assertLead(tenantId, branchId, dto.leadId);
    }

    const trip = await this.prisma.withTenant(tenantId, async (tx) => {
      const tenant = await tx.tenant.update({
        where: { id: tenantId },
        data: { tripCounter: { increment: 1 } },
        select: { tripCounter: true },
      });
      const tripCode = `TRP-${String(tenant.tripCounter).padStart(5, '0')}`;
      const created = await tx.trip.create({
        data: {
          tenantId,
          branchId,
          tripCode,
          leadId: dto.leadId ?? null,
          tripDate: dto.tripDate ? new Date(dto.tripDate) : null,
          salespersonId: dto.salespersonId,
          startingLocation: dto.startingLocation ?? null,
          startingGps: dto.startingGps ?? null,
          startingTime: dto.startingTime ?? null,
          endingLocation: dto.endingLocation ?? null,
          endingGps: dto.endingGps ?? null,
          endingTime: dto.endingTime ?? null,
          kmTravelled: dto.kmTravelled ?? 0,
          status: dto.status ?? TripStatus.PLANNED,
          notes: dto.notes ?? null,
          createdBy: actorId ?? null,
          updatedBy: actorId ?? null,
        },
      });
      if (dto.visits && dto.visits.length > 0) {
        await tx.tripVisit.createMany({
          data: dto.visits.map((v, i) => ({
            tenantId,
            tripId: created.id,
            sequence: v.sequence ?? i + 1,
            leadId: v.leadId ?? null,
            label: v.label ?? null,
            gps: v.gps ?? null,
            plannedAt: v.plannedAt ? new Date(v.plannedAt) : null,
            arrivedAt: v.arrivedAt ? new Date(v.arrivedAt) : null,
            status: v.status ?? undefined,
            notes: v.notes ?? null,
          })),
        });
      }
      return created;
    });

    return this.findById(trip.id, tenantId, branchId);
  }

  /**
   * List the active branch's trips (paginated). Optional date range (on
   * `tripDate`), salesperson, status, and case-insensitive search
   * (code/location/notes). Rows are enriched with the salesperson name, linked
   * lead code, and derived visit counts.
   * @param tenantId tenant scope
   * @param branchId active branch scope
   * @param query filters + pagination
   */
  async findAll(
    tenantId: string,
    branchId: string,
    query: ListTripsDto,
  ): Promise<PaginatedResult<TripListRow>> {
    const page = query.page ?? 1;
    const limit = query.limit ?? 20;
    const where: Prisma.TripWhereInput = {
      tenantId,
      branchId,
      deletedAt: null,
    };
    if (query.status) where.status = query.status;
    if (query.salespersonId) where.salespersonId = query.salespersonId;
    if (query.dateFrom || query.dateTo) {
      where.tripDate = {};
      if (query.dateFrom) where.tripDate.gte = new Date(query.dateFrom);
      if (query.dateTo)
        where.tripDate.lte = new Date(`${query.dateTo}T23:59:59`);
    }
    const term = query.search?.trim();
    if (term) {
      where.OR = [
        { tripCode: { contains: term, mode: 'insensitive' } },
        { startingLocation: { contains: term, mode: 'insensitive' } },
        { endingLocation: { contains: term, mode: 'insensitive' } },
        { notes: { contains: term, mode: 'insensitive' } },
      ];
    }
    const [trips, total] = await Promise.all([
      this.prisma.trip.findMany({
        where,
        skip: (page - 1) * limit,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          visits: { where: { deletedAt: null }, select: { status: true } },
          lead: { select: { leadCode: true } },
        },
      }),
      this.prisma.trip.count({ where }),
    ]);
    const nameMap = await this.staff.resolveNames(
      trips.map((t) => t.salespersonId ?? ''),
    );
    const data: TripListRow[] = trips.map((t) => {
      const { visits, lead, ...trip } = t;
      return {
        ...trip,
        ...this.countVisits(visits),
        salespersonName: t.salespersonId
          ? (nameMap.get(t.salespersonId) ?? null)
          : null,
        leadCode: lead?.leadCode ?? null,
      };
    });
    return { data, total, page, limit };
  }

  /**
   * Fetch one trip (with ordered visits, resolved names and derived counts).
   * @throws TripNotFoundException if missing/soft-deleted/other tenant
   */
  async findById(
    id: string,
    tenantId: string,
    branchId?: string,
  ): Promise<TripDetail> {
    const trip = await this.prisma.trip.findFirst({
      where: {
        id,
        tenantId,
        deletedAt: null,
        ...(branchId ? { branchId } : {}),
      },
      include: {
        visits: { where: { deletedAt: null }, orderBy: { sequence: 'asc' } },
        lead: { select: { leadCode: true } },
      },
    });
    if (!trip) {
      throw new TripNotFoundException(id);
    }
    const { visits, lead, ...rest } = trip;
    return {
      ...rest,
      ...this.countVisits(visits),
      salespersonName: await this.staff.resolveName(trip.salespersonId),
      leadCode: lead?.leadCode ?? null,
      visits,
    };
  }

  /**
   * Build the roadmap view for a trip: ordered visits plus start/end waypoints
   * and totals. Used by the Roadmap Tracking drawer.
   * @throws TripNotFoundException if missing
   */
  async roadmap(
    id: string,
    tenantId: string,
    branchId?: string,
  ): Promise<TripRoadmap> {
    const detail = await this.findById(id, tenantId, branchId);
    return {
      tripId: detail.id,
      tripCode: detail.tripCode,
      salespersonName: detail.salespersonName,
      startingLocation: detail.startingLocation,
      startingTime: detail.startingTime,
      startingGps: detail.startingGps,
      endingLocation: detail.endingLocation,
      endingTime: detail.endingTime,
      endingGps: detail.endingGps,
      kmTravelled: detail.kmTravelled,
      status: detail.status,
      visitsPlanned: detail.visitsPlanned,
      visitsCompleted: detail.visitsCompleted,
      visitsPending: detail.visitsPending,
      visitsCancelled: detail.visitsCancelled,
      visits: detail.visits,
    };
  }

  /**
   * Update a trip's own fields. `tripCode`/tenant/branch are immutable here.
   * @throws TripNotFoundException / InvalidSalespersonException
   */
  async update(
    id: string,
    tenantId: string,
    branchId: string,
    dto: UpdateTripDto,
    actorId?: string,
  ): Promise<TripDetail> {
    await this.findById(id, tenantId, branchId);
    if (dto.salespersonId) {
      await this.staff.assertSalesperson(tenantId, dto.salespersonId);
    }
    const data: Prisma.TripUpdateInput = {};
    if (dto.salespersonId !== undefined) data.salespersonId = dto.salespersonId;
    if (dto.tripDate !== undefined) {
      data.tripDate = dto.tripDate ? new Date(dto.tripDate) : null;
    }
    if (dto.startingLocation !== undefined)
      data.startingLocation = dto.startingLocation ?? null;
    if (dto.startingGps !== undefined)
      data.startingGps = dto.startingGps ?? null;
    if (dto.startingTime !== undefined)
      data.startingTime = dto.startingTime ?? null;
    if (dto.endingLocation !== undefined)
      data.endingLocation = dto.endingLocation ?? null;
    if (dto.endingGps !== undefined) data.endingGps = dto.endingGps ?? null;
    if (dto.endingTime !== undefined) data.endingTime = dto.endingTime ?? null;
    if (dto.kmTravelled !== undefined) data.kmTravelled = dto.kmTravelled;
    if (dto.status !== undefined) data.status = dto.status;
    if (dto.notes !== undefined) data.notes = dto.notes ?? null;
    if (actorId !== undefined) data.updatedBy = actorId;
    await this.prisma.withTenant(tenantId, (tx) =>
      tx.trip.update({ where: { id }, data }),
    );
    return this.findById(id, tenantId, branchId);
  }

  /**
   * Transition a trip to a new status. When the trip is linked to a lead, the
   * lead is kept in sync in the SAME transaction (CLAUDE.md §4.7): starting a
   * trip advances the lead to `MEETING_IN_PROGRESS`, completing it to
   * `MEETING_COMPLETED` (see {@link TRIP_TO_LEAD_STATUS}). Other trip statuses
   * leave the lead untouched, and a no-op write is skipped when it already
   * matches.
   * @throws TripNotFoundException if missing
   */
  async updateStatus(
    id: string,
    tenantId: string,
    branchId: string,
    status: TripStatus,
    actorId?: string,
  ): Promise<TripDetail> {
    const trip = await this.findById(id, tenantId, branchId);
    const targetLeadStatus = TRIP_TO_LEAD_STATUS[status];
    await this.prisma.withTenant(tenantId, async (tx) => {
      await tx.trip.update({
        where: { id },
        data: { status, updatedBy: actorId ?? null },
      });
      if (targetLeadStatus && trip.leadId) {
        const lead = await tx.lead.findFirst({
          where: { id: trip.leadId, tenantId, deletedAt: null },
          select: { id: true, status: true },
        });
        if (lead && lead.status !== targetLeadStatus) {
          await this.leadStatus.applyStatusInTx(
            tx,
            tenantId,
            lead.id,
            lead.status,
            targetLeadStatus,
            actorId,
            { action: `Synced from trip ${trip.tripCode} → ${status}` },
          );
        }
      }
    });
    return this.findById(id, tenantId, branchId);
  }

  /**
   * Soft-delete a trip.
   * @throws TripNotFoundException if missing
   */
  async remove(id: string, tenantId: string, branchId: string): Promise<Trip> {
    await this.findById(id, tenantId, branchId);
    return this.prisma.withTenant(tenantId, (tx) =>
      tx.trip.update({ where: { id }, data: { deletedAt: new Date() } }),
    );
  }

  /**
   * Add a visit/waypoint to a trip. When `sequence` is omitted it is appended
   * after the current max sequence.
   * @throws TripNotFoundException / InvalidTripLeadException
   */
  async addVisit(
    tripId: string,
    tenantId: string,
    branchId: string,
    dto: TripVisitDto,
  ): Promise<TripVisit> {
    await this.findById(tripId, tenantId, branchId);
    if (dto.leadId) await this.assertLead(tenantId, branchId, dto.leadId);
    let sequence = dto.sequence;
    if (sequence === undefined) {
      const max = await this.prisma.tripVisit.aggregate({
        where: { tenantId, tripId, deletedAt: null },
        _max: { sequence: true },
      });
      sequence = (max._max.sequence ?? 0) + 1;
    }
    return this.prisma.withTenant(tenantId, (tx) =>
      tx.tripVisit.create({
        data: {
          tenantId,
          tripId,
          sequence,
          leadId: dto.leadId ?? null,
          label: dto.label ?? null,
          gps: dto.gps ?? null,
          plannedAt: dto.plannedAt ? new Date(dto.plannedAt) : null,
          arrivedAt: dto.arrivedAt ? new Date(dto.arrivedAt) : null,
          status: dto.status ?? undefined,
          notes: dto.notes ?? null,
        },
      }),
    );
  }

  /**
   * Update a visit/waypoint on a trip.
   * @throws TripNotFoundException / TripVisitNotFoundException / InvalidTripLeadException
   */
  async updateVisit(
    tripId: string,
    visitId: string,
    tenantId: string,
    branchId: string,
    dto: TripVisitDto,
  ): Promise<TripVisit> {
    await this.findById(tripId, tenantId, branchId);
    const existing = await this.prisma.tripVisit.findFirst({
      where: { id: visitId, tripId, tenantId, deletedAt: null },
    });
    if (!existing) throw new TripVisitNotFoundException(visitId);
    if (dto.leadId) await this.assertLead(tenantId, branchId, dto.leadId);
    const data: Prisma.TripVisitUpdateInput = {};
    if (dto.sequence !== undefined) data.sequence = dto.sequence;
    if (dto.label !== undefined) data.label = dto.label ?? null;
    if (dto.gps !== undefined) data.gps = dto.gps ?? null;
    if (dto.plannedAt !== undefined)
      data.plannedAt = dto.plannedAt ? new Date(dto.plannedAt) : null;
    if (dto.arrivedAt !== undefined)
      data.arrivedAt = dto.arrivedAt ? new Date(dto.arrivedAt) : null;
    if (dto.status !== undefined) data.status = dto.status;
    if (dto.notes !== undefined) data.notes = dto.notes ?? null;
    return this.prisma.withTenant(tenantId, (tx) =>
      tx.tripVisit.update({ where: { id: visitId }, data }),
    );
  }

  /** Compute derived visit counts from a set of visits. */
  private countVisits(
    visits: Array<{ status: TripVisit['status'] }>,
  ): TripVisitCounts {
    return {
      visitsPlanned: visits.length,
      visitsCompleted: visits.filter((v) => v.status === 'COMPLETED').length,
      visitsPending: visits.filter(
        (v) => v.status === 'PENDING' || v.status === 'PLANNED',
      ).length,
      visitsCancelled: visits.filter((v) => v.status === 'CANCELLED').length,
    };
  }

  /**
   * Assert a lead exists and is active in the caller's tenant/branch. Reads the
   * lead directly via Prisma (no LeadService injection) to avoid a circular
   * module dependency with the lead module.
   * @throws InvalidTripLeadException if the lead is invalid for the branch
   */
  private async assertLead(
    tenantId: string,
    branchId: string,
    leadId: string,
  ): Promise<void> {
    const lead = await this.prisma.lead.findFirst({
      where: { id: leadId, tenantId, deletedAt: null },
      select: { id: true, branchId: true },
    });
    if (!lead || (lead.branchId !== null && lead.branchId !== branchId)) {
      throw new InvalidTripLeadException(leadId);
    }
  }
}
