import { PrismaClient } from '@prisma/client';
import { PDF_TEMPLATE_META_DEFAULTS } from '../src/modules/pdf-report-template/constants/pdf-template-meta.constant';

/**
 * Seed one GLOBAL (SITE_ADMIN, tenant-less) classic PDF print template per
 * supported print `type`, then best-effort clone each into every existing tenant
 * and set it as that slot's Configuration default — so the template-driven Print
 * buttons have a ready, non-empty picker and every Mustache variable can be
 * verified end-to-end.
 *
 * Idempotent: skips a global that already exists (matched by tenant-null + type +
 * name); skips a tenant clone that already exists (matched by `clonedFromId`).
 * Each template's Header/Body/Footer HTML deliberately exercises EVERY variable
 * and `{{#each}}` section its context builder emits (see the B6 catalogue), so a
 * generated PDF visibly proves each token is replaced.
 */

/** Build a complete `meta` blob (defaults + the three HTML fragments). */
function meta(
  header: string,
  body: string,
  footer: string,
): Record<string, string> {
  return {
    ...PDF_TEMPLATE_META_DEFAULTS,
    default_font: 'helvetica',
    custom_css:
      'table{width:100%;border-collapse:collapse;font-size:9pt}td,th{border:1px solid #999;padding:3px;text-align:left}h2{margin:0}.muted{color:#555}.label{display:inline-block;border:1px dashed #333;padding:6px;margin:4px;width:220px}.barcode{font-family:monospace;font-size:14pt;letter-spacing:2px}',
    header_html: header,
    body_html: body,
    footer_html: footer,
  };
}

const PATIENT_LINE =
  '<div class="muted">Patient: {patient_name} &nbsp; Age/Gender: {patient_age}/{patient_gender} &nbsp; UHID: {patient_um_id}</div>';

/** The 9 sample templates — one per supported print type. */
const TEMPLATES: Array<{
  type: string;
  name: string;
  meta: Record<string, string>;
}> = [
  {
    type: 'order_print',
    name: 'Sample Order Slip',
    meta: meta(
      '<h2>{branch_name}</h2><div>Order Slip</div>',
      `<div>Order: <b>{order_code}</b> &nbsp; Bill: {bill_id} &nbsp; Date: {order_date} {order_time} &nbsp; Status: {status}</div>
${PATIENT_LINE}
<div class="muted">Mobile: {patient_mobile} &nbsp; Email: {patient_email} &nbsp; Blood Group: {patient_blood_group}</div>
<div class="muted">Referred By: {referred_by} &nbsp; Panel: {referral_panel} &nbsp; Items: {item_count}</div>
<table><thead><tr><th>#</th><th>Name</th><th>Code</th><th>Type</th><th>Price</th><th>Disc</th></tr></thead>
<tbody>{{#each items}}<tr><td>{sr_no}</td><td>{name}</td><td>{code}</td><td>{type}</td><td>{price}</td><td>{discount}</td></tr>{{/each}}</tbody></table>`,
      '<div class="muted">Order {order_code} — generated by Kalnostics</div>',
    ),
  },
  {
    type: 'bill_print',
    name: 'Sample Patient Bill',
    meta: meta(
      '<h2>{branch_name}</h2><div>Patient Bill</div>',
      `<div>Bill: <b>{bill_id}</b> &nbsp; Order: {order_code} &nbsp; Date: {order_date} &nbsp; Status: {status} ({payment_status})</div>
${PATIENT_LINE}
<table><thead><tr><th>#</th><th>Service</th><th>Code</th><th>Price</th><th>Disc</th></tr></thead>
<tbody>{{#each items}}<tr><td>{sr_no}</td><td>{name}</td><td>{code}</td><td>{price}</td><td>{discount}</td></tr>{{/each}}</tbody></table>
<div>Gross: {gross_amount} &nbsp; Discount: {discount_amount} &nbsp; Net: <b>{net_amount}</b> &nbsp; Paid: {paid_amount} &nbsp; Balance: {balance_amount}</div>
<h4>Payments</h4>
<table><thead><tr><th>Date</th><th>Mode</th><th>Reference</th><th>Amount</th></tr></thead>
<tbody>{{#each payments}}<tr><td>{date}</td><td>{mode}</td><td>{reference}</td><td>{amount}</td></tr>{{/each}}</tbody></table>`,
      '<div class="muted">This is a computer-generated bill for order {order_code}.</div>',
    ),
  },
  {
    type: 'accounts_biling',
    name: 'Sample Accounts Billing',
    meta: meta(
      '<h2>{branch_name}</h2><div>Accounts Billing</div>',
      `<div>Bill: <b>{bill_id}</b> &nbsp; Order: {order_code} &nbsp; Date: {order_date} &nbsp; Status: {status} ({payment_status})</div>
${PATIENT_LINE}
<div class="muted">Panel: {panel_name} ({panel_code}) &nbsp; Accounts: {panel_accounts_person} &nbsp; {panel_accounts_email} &nbsp; {panel_accounts_mobile}</div>
<table><thead><tr><th>#</th><th>Service</th><th>Code</th><th>Price</th><th>Disc</th></tr></thead>
<tbody>{{#each items}}<tr><td>{sr_no}</td><td>{name}</td><td>{code}</td><td>{price}</td><td>{discount}</td></tr>{{/each}}</tbody></table>
<div>Gross: {gross_amount} &nbsp; Discount: {discount_amount} &nbsp; Net: <b>{net_amount}</b> &nbsp; Paid: {paid_amount} &nbsp; Balance: {balance_amount}</div>
<h4>Payments</h4>
<table><thead><tr><th>Date</th><th>Mode</th><th>Reference</th><th>Amount</th></tr></thead>
<tbody>{{#each payments}}<tr><td>{date}</td><td>{mode}</td><td>{reference}</td><td>{amount}</td></tr>{{/each}}</tbody></table>`,
      '<div class="muted">Accounts billing for order {order_code}.</div>',
    ),
  },
  {
    type: 'trf_print',
    name: 'Sample Test Requisition Form',
    meta: meta(
      '<h2>{branch_name}</h2><div>Test Requisition Form</div>',
      `<div>TRF Ref: <b>{trf_ref}</b> &nbsp; Order: {order_code} &nbsp; Date: {order_date}</div>
${PATIENT_LINE}
<div class="muted">Referred By: {referred_by} &nbsp; Panel: {referral_panel}</div>
<table><thead><tr><th>#</th><th>Test / Service</th><th>Code</th><th>Status</th></tr></thead>
<tbody>{{#each tests}}<tr><td>{sr_no}</td><td>{name}</td><td>{code}</td><td>{status}</td></tr>{{/each}}</tbody></table>
<h4>Clinical Notes</h4><div>{clinical_notes}</div>`,
      '<div class="muted">Sample collected by: ____________________</div>',
    ),
  },
  {
    type: 'lab_quotation_print',
    name: 'Sample Lab Quotation',
    meta: meta(
      '<h2>{branch_name}</h2><div>Quotation</div>',
      `<div>Quotation: <b>{quote_id}</b> &nbsp; Date: {quote_date} &nbsp; Valid Till: {valid_till} &nbsp; Status: {status}</div>
${PATIENT_LINE}
<div class="muted">Referred By: {referred_by} &nbsp; Panel: {referral_panel}</div>
<table><thead><tr><th>#</th><th>Service</th><th>Code</th><th>Type</th><th>Price</th></tr></thead>
<tbody>{{#each items}}<tr><td>{sr_no}</td><td>{name}</td><td>{code}</td><td>{type}</td><td>{price}</td></tr>{{/each}}</tbody></table>
<div>Gross: {gross_amount} &nbsp; Discount: {discount_amount} &nbsp; Net: <b>{net_amount}</b></div>`,
      '<div class="muted">Quotation {quote_id} — valid till {valid_till}.</div>',
    ),
  },
  {
    type: 'lab_report',
    name: 'Sample Lab Test Report',
    meta: meta(
      '<h2>{branch_name}</h2><div>Laboratory Report</div>',
      `<div>Order: <b>{order_code}</b> &nbsp; Date: {order_date}</div>
${PATIENT_LINE}
<div>Test: <b>{test_name}</b> &nbsp; Status: {report_status}</div>
<table><thead><tr><th>Result</th><th>Result 2</th><th>Unit</th><th>Method</th><th>Reference</th></tr></thead>
<tbody>{{#each results}}<tr><td>{observed1}</td><td>{observed2}</td><td>{unit}</td><td>{methodology}</td><td>{reference_display}</td></tr>{{/each}}</tbody></table>
<div class="muted">Useful For: {useful_for}</div>
<div class="muted">Interpretation: {interpretation}</div>
<div class="muted">Limitations: {limitations}</div>
<div class="muted">References: {references}</div>`,
      '<signing_authority_tag><div style="display:inline-block;margin-right:24px"><b>{name}</b><div class="muted">{designation}</div></div></signing_authority_tag>',
    ),
  },
  {
    type: 'lab_panel',
    name: 'Sample Lab Panel Report',
    meta: meta(
      '<h2>{branch_name}</h2><div>Panel Report</div>',
      `<div>Order: <b>{order_code}</b> &nbsp; Date: {order_date}</div>
${PATIENT_LINE}
<div>Panel: <b>{test_name}</b> &nbsp; Status: {report_status}</div>
<table><thead><tr><th>Result</th><th>Result 2</th><th>Unit</th><th>Method</th><th>Reference</th></tr></thead>
<tbody>{{#each results}}<tr><td>{observed1}</td><td>{observed2}</td><td>{unit}</td><td>{methodology}</td><td>{reference_display}</td></tr>{{/each}}</tbody></table>
<div class="muted">Interpretation: {interpretation}</div>`,
      '<signing_authority_tag><div style="display:inline-block;margin-right:24px"><b>{name}</b><div class="muted">{designation}</div></div></signing_authority_tag>',
    ),
  },
  {
    type: 'lab_all_report',
    name: 'Sample Lab All Reports',
    meta: meta(
      '<h2>{branch_name}</h2><div>Consolidated Report</div>',
      `<div>Order: <b>{order_code}</b> &nbsp; Date: {order_date} &nbsp; Reports: {report_count}</div>
${PATIENT_LINE}
<table><thead><tr><th>Test</th><th>Status</th><th>Results</th></tr></thead>
<tbody>{{#each reports}}<tr><td>{test_name}</td><td>{report_status}</td><td>{results_summary}</td></tr>{{/each}}</tbody></table>`,
      '<signing_authority_tag><div style="display:inline-block;margin-right:24px"><b>{name}</b><div class="muted">{designation}</div></div></signing_authority_tag>',
    ),
  },
  {
    type: 'order_label_print',
    name: 'Sample Barcode Label',
    meta: meta(
      '',
      `<div class="label">
<div class="barcode">*{barcode}*</div>
<div><b>{patient_name}</b> ({patient_age}/{patient_gender})</div>
<div class="muted">UHID: {patient_um_id}</div>
<div>{order_code} / {accession_no}</div>
<div class="muted">{sample_type} {sample_group_label}</div>
<div class="muted">Tests: {tests}</div>
<div class="muted">Collected: {collected_at}</div>
</div>`,
      '',
    ),
  },
  {
    type: 'multiple_order_label_print',
    name: 'Sample Multiple Barcode Labels',
    meta: meta(
      '',
      `{{#each labels}}<div class="label">
<div class="barcode">*{barcode}*</div>
<div><b>{patient_name}</b> ({patient_age}/{patient_gender})</div>
<div>{order_code} / {accession_no}</div>
<div class="muted">{sample_type} — Tests: {tests}</div>
</div>{{/each}}`,
      '',
    ),
  },
];

/** Seed the global sample templates + provision existing tenants (best-effort). */
export async function seedPrintTemplates(prisma: PrismaClient): Promise<void> {
  // ── 1. Global (tenant-less) sample templates ──
  const globals: Array<{ id: string; type: string }> = [];
  let createdGlobals = 0;
  for (const t of TEMPLATES) {
    let row = await prisma.pdfReportTemplate.findFirst({
      where: { tenantId: null, type: t.type, name: t.name, deletedAt: null },
      select: { id: true, type: true },
    });
    if (!row) {
      row = await prisma.pdfReportTemplate.create({
        data: {
          tenantId: null,
          branchId: null,
          type: t.type,
          name: t.name,
          isActive: true,
          meta: t.meta,
        },
        select: { id: true, type: true },
      });
      createdGlobals += 1;
    }
    globals.push(row);
  }
  console.log(
    `Seeded global print templates: ${createdGlobals} created (${TEMPLATES.length} in the set).`,
  );

  // ── 2. Best-effort: clone each global into every tenant + set config default ──
  // Tenant-scoped writes must run with the RLS tenant GUC set (mirrors
  // PrismaService.withTenant). Guarded per tenant so a fresh/empty DB or an RLS
  // hiccup never fails the whole seed.
  const tenants = await prisma.tenant.findMany({
    where: { deletedAt: null },
    select: { id: true },
  });
  if (tenants.length === 0) {
    console.log(
      'No tenants to provision print templates for (globals seeded).',
    );
    return;
  }

  let provisioned = 0;
  for (const tenant of tenants) {
    try {
      await prisma.$transaction(async (tx) => {
        await tx.$executeRawUnsafe(
          `SELECT set_config('app.current_tenant_id', '${tenant.id}', true)`,
        );
        for (const g of globals) {
          // Clone (idempotent via clonedFromId).
          let clone = await tx.pdfReportTemplate.findFirst({
            where: { tenantId: tenant.id, clonedFromId: g.id, deletedAt: null },
            select: { id: true },
          });
          if (!clone) {
            const src = TEMPLATES.find((t) => t.type === g.type)!;
            clone = await tx.pdfReportTemplate.create({
              data: {
                tenantId: tenant.id,
                branchId: null,
                clonedFromId: g.id,
                type: src.type,
                name: src.name,
                isActive: true,
                meta: src.meta,
              },
              select: { id: true },
            });
          }
          // Configuration default for this slot (idempotent).
          const cfg = await tx.pdfTemplateConfig.findFirst({
            where: {
              tenantId: tenant.id,
              branchId: null,
              slotKey: g.type,
              deletedAt: null,
            },
            select: { id: true },
          });
          if (cfg) {
            await tx.pdfTemplateConfig.update({
              where: { id: cfg.id },
              data: { templateId: clone.id },
            });
          } else {
            await tx.pdfTemplateConfig.create({
              data: {
                tenantId: tenant.id,
                branchId: null,
                slotKey: g.type,
                templateId: clone.id,
              },
            });
          }
        }
      });
      provisioned += 1;
    } catch (e) {
      console.warn(
        `Skipped print-template provisioning for tenant ${tenant.id}: ${(e as Error).message}`,
      );
    }
  }
  console.log(
    `Provisioned print templates + config defaults for ${provisioned}/${tenants.length} tenant(s).`,
  );
}
