import {
  BillingInvoiceResetCycle,
  GstMode,
  RefundApprovalLevel,
} from '@prisma/client';
import {
  IsBoolean,
  IsEnum,
  IsInt,
  IsOptional,
  IsString,
  Matches,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

/**
 * Save/upsert payload for Registration billing settings. All fields are optional
 * so the frontend can patch a single card or submit the whole form.
 */
export class SaveBillingSettingsDto {
  @IsOptional()
  @IsString()
  @MaxLength(24)
  @Matches(/^[A-Za-z0-9\-_/]*$/, {
    message: 'invoicePrefix may only contain letters, digits, - _ /',
  })
  invoicePrefix?: string;

  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(2147483647)
  nextInvoiceNumber?: number;

  @IsOptional()
  @IsEnum(BillingInvoiceResetCycle)
  invoiceResetCycle?: BillingInvoiceResetCycle;

  @IsOptional()
  @IsString()
  @MaxLength(512)
  receiptFooter?: string;

  @IsOptional()
  @IsEnum(GstMode)
  gstMode?: GstMode;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(100)
  defaultGstPercent?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(100)
  counterDiscountMax?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(100)
  managerDiscountMax?: number;

  @IsOptional()
  @IsBoolean()
  isApprovalRequiredAboveCounterLimit?: boolean;

  @IsOptional()
  @IsBoolean()
  isLineItemDiscountAllowed?: boolean;

  @IsOptional()
  @IsBoolean()
  isCashEnabled?: boolean;

  @IsOptional()
  @IsBoolean()
  isCardEnabled?: boolean;

  @IsOptional()
  @IsBoolean()
  isUpiEnabled?: boolean;

  @IsOptional()
  @IsBoolean()
  isWalletEnabled?: boolean;

  @IsOptional()
  @IsBoolean()
  isBankTransferEnabled?: boolean;

  @IsOptional()
  @IsBoolean()
  isCreditB2bEnabled?: boolean;

  @IsOptional()
  @IsEnum(RefundApprovalLevel)
  refundApprovalLevel?: RefundApprovalLevel;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(3650)
  refundWindowDays?: number;

  @IsOptional()
  @IsBoolean()
  isCreditNoteAutoGeneratedOnRefund?: boolean;

  @IsOptional()
  @IsBoolean()
  isRefundBlockedAfterReportDispatch?: boolean;
}
