-- Expand ContainerType with the 35 container descriptions from the "New UI
-- Improvements" workbook's SAMPLE tab. Additive only — the existing 11 values
-- are kept unchanged so rows created before this change stay valid; there is
-- no equivalent old value for most of these (e.g. blood culture bottles, glass
-- slides, filter paper cards), so nothing is renamed or removed.
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'URINE_24H_CONTAINER_NO_PRESERVATIVE';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'URINE_24H_CONTAINER_ACETIC_ACID';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'URINE_24H_CONTAINER_HYDROCHLORIC_ACID';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'URINE_24H_CONTAINER_BORIC_ACID';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'URINE_24H_CONTAINER_DIAZOLIDINYL_UREA';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'URINE_24H_CONTAINER_SODIUM_CARBONATE';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'ANAEROBIC_TRANSPORT_VIAL';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'BLOOD_CULTURE_BOTTLE_AEROBIC';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'BLOOD_CULTURE_BOTTLE_ANAEROBIC';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'BLOOD_CULTURE_BOTTLE_PEDIATRIC';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'CLEAN_PAPER_ENVELOPE_PACKET';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'CULTURE_PLATE_BROTH_VIAL';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'GLASS_SLIDES_WITH_FIXATIVE_SLIDE_JAR';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'K2_K3_EDTA_TUBE_LAVENDER_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'LIQUID_BASED_CYTOLOGY_VIAL';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'LITHIUM_HEPARIN_TUBE_GREEN_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'PLAIN_CLOT_ACTIVATOR_TUBE_RED_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'PPT_PLASMA_PREP_TUBE_PEARL_WHITE_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'ROYAL_BLUE_TRACE_ELEMENT_TUBE';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'SST_TUBE_WITH_GEL_GOLD_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'SODIUM_CITRATE_TUBE_32PCT_LIGHT_BLUE_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'SODIUM_CITRATE_TUBE_38PCT_ESR_BLACK_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'SODIUM_FLUORIDE_OXALATE_TUBE_GREY_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'SODIUM_HEPARIN_TUBE_GREEN_TOP';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'STERILE_CONTAINER_NEUTRAL_BUFFERED_FORMALIN';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'STERILE_CONTAINER_GLUTARALDEHYDE';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'STERILE_CONTAINER_CARY_BLAIR_MEDIUM';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'STERILE_CONTAINER_MICHELS_ZEUS_MEDIUM';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'STERILE_CONTAINER_NORMAL_SALINE_FRESH';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'STERILE_DRY_SWAB_CONTAINER';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'STERILE_UNIVERSAL_WIDE_MOUTH_CONTAINER';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'SWEAT_COLLECTION_DEVICE_MACRODUCT';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'SWAB_TUBE_AMIES_STUART_MEDIUM';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'SWAB_TUBE_VIRAL_TRANSPORT_MEDIUM';
ALTER TYPE "ContainerType" ADD VALUE IF NOT EXISTS 'WHATMAN_903_FILTER_PAPER_CARD';
