import { Injectable } from '@nestjs/common';
import {
  FollowUp,
  FollowUpStatus,
  LeadPriority,
  LeadStatus,
  Prisma,
} from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { PaginatedResult } from '../../common/dto/response.dto';
import { SalesStaffService } from '../sales-trip/sales-staff.service';
import { SalesLeadStatusService } from '../sales-trip/sales-lead-status.service';
import { CreateFollowUpDto } from './dto/create-follow-up.dto';
import { UpdateFollowUpDto } from './dto/update-follow-up.dto';
import {
  FollowUpStatusBucket,
  ListFollowUpsDto,
} from './dto/list-follow-ups.dto';
import {
  FollowUpNotFoundException,
  InvalidFollowUpLeadException,
  InvalidFollowUpTripException,
} from './exceptions/sales-follow-up.exceptions';
import { FollowUpDetail, FollowUpListRow } from './entities/follow-up.entity';

/** Map a list `statusBucket` to its `FollowUpStatus` (`all` = no filter). */
const BUCKET_TO_STATUS: Record<
  Exclude<FollowUpStatusBucket, 'all'>,
  FollowUpStatus
> = {
  scheduled: FollowUpStatus.SCHEDULED,
  pending: FollowUpStatus.PENDING,
  completed: FollowUpStatus.COMPLETED,
  converted: FollowUpStatus.CONVERTED,
  cancelled: FollowUpStatus.CANCELLED,
  rescheduled: FollowUpStatus.RESCHEDULED,
  'no-response': FollowUpStatus.NO_RESPONSE,
};

/**
 * Follow-up status → the parent lead status it drives (unmapped statuses —
 * `PENDING`, `CANCELLED`, `RESCHEDULED`, `NO_RESPONSE` — leave the lead as-is).
 */
const FOLLOWUP_TO_LEAD_STATUS: Partial<Record<FollowUpStatus, LeadStatus>> = {
  [FollowUpStatus.SCHEDULED]: LeadStatus.FOLLOW_UP_REQUIRED,
  [FollowUpStatus.COMPLETED]: LeadStatus.MEETING_COMPLETED,
  [FollowUpStatus.CONVERTED]: LeadStatus.CONVERTED,
};

/**
 * Sales follow-ups. Tenant-scoped + branch-level (CLAUDE.md §4.7): every query
 * carries `tenantId`/`branchId` and filters soft-deleted rows. The `followUpCode`
 * (`FU-#####`) is a per-tenant sequential code generated atomically. Each
 * follow-up hangs off a lead (required) and may reference the trip it was
 * scheduled during; status transitions are recorded in `FollowUpStatusHistory`.
 */
@Injectable()
export class SalesFollowUpService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly staff: SalesStaffService,
    private readonly leadStatus: SalesLeadStatusService,
  ) {}

  /**
   * Create a follow-up at the active branch. Validates the `leadId` (required)
   * and, when supplied, the `tripId` against the caller's tenant/branch, plus the
   * assigned salesperson. The `followUpCode` is generated by atomically
   * incrementing `Tenant.followUpCounter` in the same transaction, so concurrent
   * creates never collide. Seeds an initial status-history row.
   * @param tenantId tenant scope
   * @param branchId active branch (from JWT)
   * @param dto validated follow-up payload (no code/tenant/branch — set here)
   * @param actorId person id of the creator (audit trail)
   * @returns the created follow-up enriched with names + status history
   * @throws InvalidFollowUpLeadException if `leadId` is invalid for the branch
   * @throws InvalidFollowUpTripException if `tripId` is invalid for the branch
   * @throws InvalidSalespersonException if the salesperson is not active staff
   */
  async create(
    tenantId: string,
    branchId: string,
    dto: CreateFollowUpDto,
    actorId?: string,
  ): Promise<FollowUpDetail> {
    await this.assertLead(tenantId, branchId, dto.leadId);
    if (dto.tripId) {
      await this.assertTrip(tenantId, branchId, dto.tripId);
    }
    if (dto.assignedSalespersonId) {
      await this.staff.assertSalesperson(tenantId, dto.assignedSalespersonId);
    }

    const followUp = await this.prisma.withTenant(tenantId, (tx) =>
      this.createInTx(tx, tenantId, branchId, dto, actorId),
    );

    return this.findById(followUp.id, tenantId, branchId);
  }

  /**
   * Insert a follow-up (+ its seed status-history row) on an EXISTING tenant
   * transaction, atomically incrementing the per-tenant `FU-#####` counter. The
   * caller MUST already run inside `prisma.withTenant` (so RLS + rollback apply)
   * and MUST have validated `leadId`/`tripId`/salesperson beforehand.
   *
   * Shared by {@link create} and by the lead meeting-outcome flow, where a
   * "Follow-up Required" outcome auto-creates a follow-up in the SAME
   * transaction as the lead update — so if either write fails, both roll back.
   * @param tx the caller's transaction-scoped Prisma client
   * @param tenantId tenant scope
   * @param branchId active branch (from JWT)
   * @param dto validated follow-up payload
   * @param actorId person id of the creator (audit trail)
   * @returns the created follow-up row
   */
  async createInTx(
    tx: Prisma.TransactionClient,
    tenantId: string,
    branchId: string,
    dto: CreateFollowUpDto,
    actorId?: string,
  ): Promise<FollowUp> {
    const status = dto.status ?? FollowUpStatus.SCHEDULED;
    const tenant = await tx.tenant.update({
      where: { id: tenantId },
      data: { followUpCounter: { increment: 1 } },
      select: { followUpCounter: true },
    });
    const followUpCode = `FU-${String(tenant.followUpCounter).padStart(5, '0')}`;
    const created = await tx.followUp.create({
      data: {
        tenantId,
        branchId,
        followUpCode,
        leadId: dto.leadId,
        tripId: dto.tripId ?? null,
        type: dto.type,
        priority: dto.priority ?? LeadPriority.MEDIUM,
        dueAt: dto.dueAt ? new Date(dto.dueAt) : null,
        requirement: dto.requirement ?? null,
        lastDiscussion: dto.lastDiscussion ?? null,
        nextAction: dto.nextAction ?? null,
        status,
        assignedSalespersonId: dto.assignedSalespersonId ?? null,
        createdBy: actorId ?? null,
        updatedBy: actorId ?? null,
      },
    });
    await tx.followUpStatusHistory.create({
      data: {
        tenantId,
        followUpId: created.id,
        action: 'Follow-up created',
        toStatus: status,
        byPersonId: actorId ?? null,
      },
    });
    return created;
  }

  /**
   * List the active branch's follow-ups (paginated). Optional due-date range,
   * salesperson, priority, status/status-bucket, lead, and case-insensitive
   * search (code/requirement/next action). Rows are enriched with the salesperson
   * name and linked lead code.
   * @param tenantId tenant scope
   * @param branchId active branch scope
   * @param query filters + pagination
   */
  async findAll(
    tenantId: string,
    branchId: string,
    query: ListFollowUpsDto,
  ): Promise<PaginatedResult<FollowUpListRow>> {
    const page = query.page ?? 1;
    const limit = query.limit ?? 20;
    const where: Prisma.FollowUpWhereInput = {
      tenantId,
      branchId,
      deletedAt: null,
    };
    const status = this.resolveStatusFilter(query);
    if (status) where.status = status;
    if (query.priority) where.priority = query.priority;
    if (query.salespersonId) where.assignedSalespersonId = query.salespersonId;
    if (query.leadId) where.leadId = query.leadId;
    if (query.dateFrom || query.dateTo) {
      where.dueAt = {};
      if (query.dateFrom) where.dueAt.gte = new Date(query.dateFrom);
      if (query.dateTo) where.dueAt.lte = new Date(`${query.dateTo}T23:59:59`);
    }
    const term = query.search?.trim();
    if (term) {
      where.OR = [
        { followUpCode: { contains: term, mode: 'insensitive' } },
        { requirement: { contains: term, mode: 'insensitive' } },
        { lastDiscussion: { contains: term, mode: 'insensitive' } },
        { nextAction: { contains: term, mode: 'insensitive' } },
      ];
    }
    const [followUps, total] = await Promise.all([
      this.prisma.followUp.findMany({
        where,
        skip: (page - 1) * limit,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: { lead: { select: { leadCode: true } } },
      }),
      this.prisma.followUp.count({ where }),
    ]);
    const nameMap = await this.staff.resolveNames(
      followUps.map((f) => f.assignedSalespersonId ?? ''),
    );
    const data: FollowUpListRow[] = followUps.map((f) => {
      const { lead, ...followUp } = f;
      return {
        ...followUp,
        salespersonName: f.assignedSalespersonId
          ? (nameMap.get(f.assignedSalespersonId) ?? null)
          : null,
        leadCode: lead?.leadCode ?? null,
      };
    });
    return { data, total, page, limit };
  }

  /**
   * Fetch one follow-up (with ordered status history + resolved names).
   * @throws FollowUpNotFoundException if missing/soft-deleted/other tenant
   */
  async findById(
    id: string,
    tenantId: string,
    branchId?: string,
  ): Promise<FollowUpDetail> {
    const followUp = await this.prisma.followUp.findFirst({
      where: {
        id,
        tenantId,
        deletedAt: null,
        ...(branchId ? { branchId } : {}),
      },
      include: {
        statusHistory: { orderBy: { createdAt: 'asc' } },
        lead: { select: { leadCode: true } },
      },
    });
    if (!followUp) {
      throw new FollowUpNotFoundException(id);
    }
    const { statusHistory, lead, ...rest } = followUp;
    return {
      ...rest,
      salespersonName: await this.staff.resolveName(rest.assignedSalespersonId),
      leadCode: lead?.leadCode ?? null,
      statusHistory,
    };
  }

  /**
   * Update a follow-up's own fields. `followUpCode`/`leadId`/tenant/branch are
   * immutable here; status transitions with history use `updateStatus`.
   * @throws FollowUpNotFoundException / InvalidFollowUpTripException /
   *   InvalidSalespersonException
   */
  async update(
    id: string,
    tenantId: string,
    branchId: string,
    dto: UpdateFollowUpDto,
    actorId?: string,
  ): Promise<FollowUpDetail> {
    await this.findById(id, tenantId, branchId);
    if (dto.tripId) {
      await this.assertTrip(tenantId, branchId, dto.tripId);
    }
    if (dto.assignedSalespersonId) {
      await this.staff.assertSalesperson(tenantId, dto.assignedSalespersonId);
    }
    const data: Prisma.FollowUpUpdateInput = {};
    if (dto.tripId !== undefined) {
      data.trip = dto.tripId
        ? { connect: { id: dto.tripId } }
        : { disconnect: true };
    }
    if (dto.type !== undefined) data.type = dto.type;
    if (dto.priority !== undefined) data.priority = dto.priority;
    if (dto.dueAt !== undefined) {
      data.dueAt = dto.dueAt ? new Date(dto.dueAt) : null;
    }
    if (dto.requirement !== undefined)
      data.requirement = dto.requirement ?? null;
    if (dto.lastDiscussion !== undefined)
      data.lastDiscussion = dto.lastDiscussion ?? null;
    if (dto.nextAction !== undefined) data.nextAction = dto.nextAction ?? null;
    if (dto.assignedSalespersonId !== undefined)
      data.assignedSalespersonId = dto.assignedSalespersonId ?? null;
    if (dto.status !== undefined) data.status = dto.status;
    if (actorId !== undefined) data.updatedBy = actorId;
    await this.prisma.withTenant(tenantId, (tx) =>
      tx.followUp.update({ where: { id }, data }),
    );
    return this.findById(id, tenantId, branchId);
  }

  /**
   * Transition a follow-up to a new status and record it in the status history
   * (from/to status, actor, remarks). When the follow-up drives a lead status
   * (see {@link FOLLOWUP_TO_LEAD_STATUS}), the parent lead is kept in sync in the
   * SAME transaction (CLAUDE.md §4.7): `SCHEDULED` → `FOLLOW_UP_REQUIRED`,
   * `COMPLETED` → `MEETING_COMPLETED`, `CONVERTED` → `CONVERTED`. Unmapped
   * statuses leave the lead untouched, and a no-op write is skipped when it
   * already matches.
   * @throws FollowUpNotFoundException if missing
   */
  async updateStatus(
    id: string,
    tenantId: string,
    branchId: string,
    status: FollowUpStatus,
    remarks?: string,
    actorId?: string,
  ): Promise<FollowUpDetail> {
    const existing = await this.findById(id, tenantId, branchId);
    const targetLeadStatus = FOLLOWUP_TO_LEAD_STATUS[status];
    await this.prisma.withTenant(tenantId, async (tx) => {
      await tx.followUp.update({
        where: { id },
        data: { status, updatedBy: actorId ?? null },
      });
      await tx.followUpStatusHistory.create({
        data: {
          tenantId,
          followUpId: id,
          action: `Status → ${status}`,
          fromStatus: existing.status,
          toStatus: status,
          byPersonId: actorId ?? null,
          remarks: remarks ?? null,
        },
      });
      if (targetLeadStatus && existing.leadId) {
        const lead = await tx.lead.findFirst({
          where: { id: existing.leadId, tenantId, deletedAt: null },
          select: { id: true, status: true },
        });
        if (lead && lead.status !== targetLeadStatus) {
          await this.leadStatus.applyStatusInTx(
            tx,
            tenantId,
            lead.id,
            lead.status,
            targetLeadStatus,
            actorId,
            {
              action: `Synced from follow-up ${existing.followUpCode} → ${status}`,
            },
          );
        }
      }
    });
    return this.findById(id, tenantId, branchId);
  }

  /**
   * Soft-delete a follow-up.
   * @throws FollowUpNotFoundException if missing
   */
  async remove(
    id: string,
    tenantId: string,
    branchId: string,
    actorId?: string,
  ): Promise<FollowUp> {
    await this.findById(id, tenantId, branchId);
    return this.prisma.withTenant(tenantId, (tx) =>
      tx.followUp.update({
        where: { id },
        data: { deletedAt: new Date(), updatedBy: actorId ?? null },
      }),
    );
  }

  /**
   * Resolve the effective status filter: explicit `status` wins over the
   * `statusBucket` shortcut; `all`/absent means no filter.
   */
  private resolveStatusFilter(
    query: ListFollowUpsDto,
  ): FollowUpStatus | undefined {
    if (query.status) return query.status;
    if (query.statusBucket && query.statusBucket !== 'all') {
      return BUCKET_TO_STATUS[query.statusBucket];
    }
    return undefined;
  }

  /**
   * Assert a lead exists and is active in the caller's tenant/branch. Reads the
   * lead directly via Prisma (no LeadService injection) to avoid a circular
   * module dependency with the lead module.
   * @throws InvalidFollowUpLeadException if the lead is invalid for the branch
   */
  private async assertLead(
    tenantId: string,
    branchId: string,
    leadId: string,
  ): Promise<void> {
    const lead = await this.prisma.lead.findFirst({
      where: { id: leadId, tenantId, deletedAt: null },
      select: { id: true, branchId: true },
    });
    if (!lead || (lead.branchId !== null && lead.branchId !== branchId)) {
      throw new InvalidFollowUpLeadException(leadId);
    }
  }

  /**
   * Assert a trip exists and is active in the caller's tenant/branch.
   * @throws InvalidFollowUpTripException if the trip is invalid for the branch
   */
  private async assertTrip(
    tenantId: string,
    branchId: string,
    tripId: string,
  ): Promise<void> {
    const trip = await this.prisma.trip.findFirst({
      where: { id: tripId, tenantId, deletedAt: null },
      select: { id: true, branchId: true },
    });
    if (!trip || (trip.branchId !== null && trip.branchId !== branchId)) {
      throw new InvalidFollowUpTripException(tripId);
    }
  }
}
